namespace Forwarder;

internal static class ForwardAttributeSourceProvider
{
    public const string Namespace = "Forwarder";
    public const string AttributeName = "ForwardAttribute";

    public const string AttributeSourceCode = $@"// <auto-generated/>
namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Field)]
    public class {AttributeName} : System.Attribute
    {{
    }}
}}";
}