name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change this if you're using a different version

      - name: Restore dependencies
        run: dotnet restore Forwarder/Forwarder.Tests/Forwarder.Tests.csproj

      - name: Build
        run: dotnet build Forwarder/Forwarder.Tests/Forwarder.Tests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Forwarder/Forwarder.Tests/Forwarder.Tests.csproj --no-build --configuration Release --verbosity normal